//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Pakistan_With_Us.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirLineInformation
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }
        public string TimeDuration { get; set; }
        public string DepartingTime { get; set; }
        public Nullable<int> TicketPrice { get; set; }
    }
}
