//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Pakistan_With_Us.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TrainBooking
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Please Select Arival From.")]
        public string ArivalFrom { get; set; }

        [Required(ErrorMessage = "Please Select Arival To.")]
        public string ArivalTo { get; set; }

        [Required(ErrorMessage = "Please Enter CNIC.")]
        [RegularExpression("^[0-9]{5}-[0-9]{7}-[0-9]$", ErrorMessage = "CNIC No must follow the XXXXX-XXXXXXX-X format!")]
        public string CNIC { get; set; }
       
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression("^[0-9]{4}-[0-9]{7}$", ErrorMessage = "Entered phone format is not valid.")]

        //[RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",ErrorMessage = "Entered phone format is not valid.")]
        public string PhoneNumber { get; set; }


        [Required(ErrorMessage = "Please Select Time Slot.")]
        public string TimeSlot { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Start date and time cannot be empty")]
        public Nullable<System.DateTime> Departing { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "End date and time cannot be empty")]
        public Nullable<System.DateTime> Returing { get; set; }


        [Required(ErrorMessage = "Please Select Train.")]
        public string SelectTrain { get; set; }

        [Required(ErrorMessage = "Please Select Ticket.")]
        public Nullable<int> SelectTicket { get; set; }

        [ForeignKey("UserID")]
        public string User_id { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
